# .github/workflows/cicd.yml

name: Build and Deploy to Minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/public-garden-app:${{ github.sha }}

      - name: Deploy to Minikube
        run: |
          echo "Deploying to Minikube..."
          # This command now explicitly tells kubectl where to find the configuration
          # file needed to connect to your Minikube cluster.
          kubectl set image deployment/public-garden-deployment public-garden-container=${{ secrets.DOCKERHUB_USERNAME }}/public-garden-app:${{ github.sha }} -n public-garden-app --kubeconfig="C:\Users\ereza\.kube\config"

