# .github/workflows/cicd.yml

name: Build and Deploy to Minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/public-garden-app:${{ github.sha }}

      # New Step: Securely write the kubeconfig from secrets to a temporary file
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/kubeconfig
        shell: bash

      # Final Step: Use the new temporary kubeconfig file for deployment
      - name: Deploy to Minikube
        run: |
          echo "Deploying to Minikube..."
          kubectl set image deployment/public-garden-deployment public-garden-container=${{ secrets.DOCKERHUB_USERNAME }}/public-garden-app:${{ github.sha }} -n public-garden-app --kubeconfig=$HOME/kubeconfig
        shell: bash

