# .github/workflows/cicd.yml

name: Build and Deploy to Minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/public-garden-app:${{ github.sha }}

      # This action correctly handles the KUBE_CONFIG secret and sets up the context for kubectl.
      - name: Set up Kubeconfig
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      # The --kubeconfig flag is no longer needed because the action above handles it.
      - name: Deploy to Minikube
        run: |
          echo "Deploying to Minikube..."
          kubectl set image deployment/public-garden-deployment public-garden-container=${{ secrets.DOCKERHUB_USERNAME }}/public-garden-app:${{ github.sha }} -n public-garden-app
