# .github/workflows/cicd.yml

name: Build and Deploy to Minikube

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/public-garden-app:${{ github.sha }}

      # New Step: Securely write the kubeconfig to a temporary file using PowerShell
      - name: Set up Kubeconfig
        run: |
          "${{ secrets.KUBE_CONFIG }}" | Set-Content -Path "$env:HOMEPATH\kubeconfig"
        # No 'shell: bash' here, so it defaults to PowerShell on Windows

      # Final Step: Use the new kubeconfig file for deployment using PowerShell
      - name: Deploy to Minikube
        run: |
          echo "Deploying to Minikube..."
          kubectl set image deployment/public-garden-deployment public-garden-container=${{ secrets.DOCKERHUB_USERNAME }}/public-garden-app:${{ github.sha }} -n public-garden-app --kubeconfig="$env:HOMEPATH\kubeconfig"
        # No 'shell: bash' here either

